//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoterWalletMobile {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SoterWalletMobile.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        public static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string EnterCurrentPin {
            get {
                return ResourceManager.GetString("EnterCurrentPin", resourceCulture);
            }
        }
        
        public static string EnterNewPin {
            get {
                return ResourceManager.GetString("EnterNewPin", resourceCulture);
            }
        }
        
        public static string ReEnterCurrentPin {
            get {
                return ResourceManager.GetString("ReEnterCurrentPin", resourceCulture);
            }
        }
        
        public static string EnterButton {
            get {
                return ResourceManager.GetString("EnterButton", resourceCulture);
            }
        }
        
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        public static string PinPageHintMessage {
            get {
                return ResourceManager.GetString("PinPageHintMessage", resourceCulture);
            }
        }
        
        public static string SetLabelMessage {
            get {
                return ResourceManager.GetString("SetLabelMessage", resourceCulture);
            }
        }
        
        public static string InitializeDeviceMessage {
            get {
                return ResourceManager.GetString("InitializeDeviceMessage", resourceCulture);
            }
        }
        
        public static string RecoverSentenceMessage {
            get {
                return ResourceManager.GetString("RecoverSentenceMessage", resourceCulture);
            }
        }
        
        public static string ConfirmWipeMessage {
            get {
                return ResourceManager.GetString("ConfirmWipeMessage", resourceCulture);
            }
        }
    }
}
